name: Test valgrind

on:
  schedule:
    - cron: '13 6 * * *'
  workflow_dispatch:

jobs:

  valgrind:
    name: Test valgrind
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: test_mupdf-master-branch
        run:
          python scripts/test.py -m 'git:--recursive --depth 1 --shallow-submodules --branch master https://github.com/ArtifexSoftware/mupdf.git' --valgrind 1 buildtest
