name: Test quick

on:
  pull_request:
    branches: [main]
    
  workflow_dispatch:

jobs:

  test_quick:
    name: Test quick
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # We test on just Ubuntu, with hard-coded MuPDF, MuPDF master, and current MuPDF branch.
        #
        os: [ubuntu-latest]
        environment: [
                '',
                'PYMUPDF_SETUP_MUPDF_TGZ="" PYMUPDF_SETUP_MUPDF_BUILD="git:--recursive --depth 1 --shallow-submodules --branch master https://github.com/ArtifexSoftware/mupdf.git"',
                'PYMUPDF_SETUP_MUPDF_TGZ="" PYMUPDF_SETUP_MUPDF_BUILD="git:--recursive --depth 1 --shallow-submodules --branch 1.22.x https://github.com/ArtifexSoftware/mupdf.git"',
                ]

      # Avoid cancelling of all cibuildwheel runs after a single failure.
      fail-fast: false

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      
      - name: cibuildwheel
        uses: pypa/cibuildwheel@v2.11.2

        env:
            CIBW_ENVIRONMENT: ${{matrix.environment}}

            # Build on single cpu.
            CIBW_ARCHS_LINUX: x86_64

            # Build for single python version.
            CIBW_BUILD: "cp311*"

            # Don't build for unsupported platforms or win32.
            CIBW_SKIP: "pp* *i686 *-musllinux_* cp36* *win32*"

            # Get cibuildwheel to run pytest with each wheel.
            CIBW_TEST_REQUIRES: "fontTools pytest"
            CIBW_TEST_COMMAND: "pytest -s {project}/tests"
            CIBW_BUILD_VERBOSITY: 3
