name: Test sysinstall

on:
  schedule:
    - cron: '13 4 * * *'
  workflow_dispatch:

jobs:

  sysinstall:
    name: Test sysinstall
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          # 3.12 doesn't have setuptools. As of 2024-01-03, MuPDF build requires setuptools before it
          # sees `--venv` and defers to a venv, so we currently have to force use of python 3.11.
          python-version: '3.11'

      - name: sysinstall
        run:
          python scripts/sysinstall.py --mupdf-git '--branch master https://github.com/ArtifexSoftware/mupdf.git'
